### PR TITLE
Scrapy Support

### PR DESCRIPTION
**Pull request by jtopjian**

### CODE REVIEW

**Comment by jtopjian** [comment]
@ianabc I added these to `pims-minimal` - not sure if that is the best place.

This successfully builds and the new tests check out. I have not pushed the images yet.

**Comment by ianabc** [comment]
I think pims-minimal is the right image for these. I haven't tried out the tests yet, but if they're passing I think this can be merged.

**Comment by jtopjian** [comment]
Sounds good. Should I also push the images to docker hub or wait?

**Comment by ianabc** [comment]
I think just push them when you're ready.

**Pull request merged**
